### ISSUE TITLE
Need help

### ISSUE THREAD

**Issue by tumashu** [sp4rkie/debian-on-termux#7] opened 2017-11-23 03:25 UTC
I: Extracting libmount1...
I: Extracting libsmartcols1...
I: Extracting libuuid1...
I: Extracting mount...
I: Extracting util-linux...
I: Extracting liblzma5...
I: Extracting zlib1g...
I: Keyring file not available at /usr/share/keyrings/debian-archive-keyring.gpg; switching to https mirror https://deb.debian.org/debian
I: Installing core packages...
W: Failure trying to run:  dpkg --force-depends --install /var/cache/apt/archives/base-passwd_3.5.43_arm64.deb
W: See //debootstrap/debootstrap.log for details
update-alternatives: error: no alternatives for editor
info: Trying to set 'debconf/frontend' [select] to 'Editor'
info: Loading answer for 'debconf/frontend'
info: Trying to set 'debconf/priority' [select] to 'low'
info: Loading answer for 'debconf/priority'
info: Trying to set 'locales/locales_to_be_generated' [select] to 'en_US.UTF-8 UTF-8'
info: Loading answer for 'locales/locales_to_be_generated'
info: Trying to set 'locales/default_environment_locale' [select] to 'en_US.UTF-8'
info: Loading answer for 'locales/default_environment_locale'
dpkg-query: warning: parsing file '/var/lib/dpkg/status' near line 5 package 'dpkg':
 missing description
dpkg-query: warning: parsing file '/var/lib/dpkg/status' near line 5 package 'dpkg':
 missing architecture
dpkg-query: error: unable to read file triggers file '/var/lib/dpkg/triggers/File': Bad address
dpkg-query: warning: parsing file '/var/lib/dpkg/status' near line 5 package 'dpkg':
 missing description
dpkg-query: warning: parsing file '/var/lib/dpkg/status' near line 5 package 'dpkg':
 missing architecture
dpkg-query: error: unable to read file triggers file '/var/lib/dpkg/triggers/File': Bad address
/usr/sbin/dpkg-reconfigure: tzdata is not installed
dpkg-query: warning: parsing file '/var/lib/dpkg/status' near line 5 package 'dpkg':
 missing description
dpkg-query: warning: parsing file '/var/lib/dpkg/status' near line 5 package 'dpkg':
 missing architecture
dpkg-query: error: unable to read file triggers file '/var/lib/dpkg/triggers/File': Bad address
dpkg-query: warning: parsing file '/var/lib/dpkg/status' near line 5 package 'dpkg':
 missing description
dpkg-query: warning: parsing file '/var/lib/dpkg/status' near line 5 package 'dpkg':
 missing architecture
dpkg-query: error: unable to read file triggers file '/var/lib/dpkg/triggers/File': Bad address
/usr/sbin/dpkg-reconfigure: debconf is not installed
/tmp/dot_tmp.sh: 26: /tmp/dot_tmp.sh: apt: not found
/tmp/dot_tmp.sh: 27: /tmp/dot_tmp.sh: apt: not found
/tmp/dot_tmp.sh: 28: /tmp/dot_tmp.sh: apt: not found
/tmp/dot_tmp.sh: 29: /tmp/dot_tmp.sh: update-locale: not found
/tmp/dot_tmp.sh: 34: /tmp/dot_tmp.sh: apt: not found

installation successfully completed
to enter the guest system type:
$HOME/bin/enter_deb

**Comment by sp4rkie** [comment] 2017-11-23 12:07
just must edit your 'ARCHITECTURE' (near the top of the script) accordingly.

**Comment by tumashu** [comment] 2017-11-23 12:32
```
3.10.86-g55f77f8
$ uname -a
Linux localhost 3.10.86-g55f77f8 #2 SMP PREEMPT Thu Oct 12 11:53:24 CST 2017 aarch64 Android
$
```

I have edited it to arm64

**Comment by sp4rkie** [comment] 2017-11-23 13:43
what is the output of

    egrep wget debian_on_termux.sh

**Comment by tumashu** [comment] 2017-11-23 15:11
```
wget http://http.debian.net/debian/pool/main/d/debootstrap/debootstrap_1.0.92.tar.gz -O - | tar xfz -

```

**Comment by sp4rkie** [comment] 2017-11-23 15:25
sometimes 'proot' program (of the 'proot' package) does not work properly. Did you update the termux packages (including 'proot') to the most recent ones via 'apt update; apt upgrade'? 
After the upgrade please retry executing 'debian_on_termux.sh'.

**Comment by sp4rkie** [comment] 2017-11-25 05:50
what is the status now? Did you retry?

**Comment by tumashu** [comment] 2017-11-25 09:24
```
what is the status now? Did you retry?
```
The same problem ....

**Comment by sp4rkie** [comment] 2017-11-26 05:59
what does '$HOME/deboot_debian/debootstrap/debootstrap.log' say at the time of error?

**Comment by tumashu** [comment] 2017-11-27 01:28
```
bash-4.4$ sh debian_on_termux.sh
the target install directory already exists, to continue please remove it by
rm -rf /data/data/com.termux/files/home/deboot_debian
bash-4.4$ rm -rf /data/data/com.termux/files/home/deboot_debian
bash-4.4$ sh debian_on_termux.sh
Hit:1 http://mirrors.tuna.tsinghua.edu.cn/termux stable InRelease
Reading package lists...
Building dependency tree...
Reading state information...
All packages are up to date.
Reading package lists...
Building dependency tree...
Reading state information...
perl is already the newest version (5.26.1).
proot is already the newest version (5.1.106-5).
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
--2017-11-27 08:26:47--  http://http.debian.net/debian/pool/main/d/debootstrap/debootstrap_1.0.92.tar.gz
Resolving http.debian.net... 128.31.0.62, 149.20.4.15, 130.89.148.14, ...
Connecting to http.debian.net|128.31.0.62|:80... connected.
HTTP request sent, awaiting response... 302 Found
Location: http://cdn-fastly.deb.debian.org/debian/pool/main/d/debootstrap/debootstrap_1.0.92.tar.gz [following]
--2017-11-27 08:26:51--  http://cdn-fastly.deb.debian.org/debian/pool/main/d/debootstrap/debootstrap_1.0.92.tar.gz
Resolving cdn-fastly.deb.debian.org... 151.101.72.204, 2a04:4e42:11::204
Connecting to cdn-fastly.deb.debian.org|151.101.72.204|:80... connected.
HTTP request sent, awaiting response... 200 OK
Length: 70042 (68K) [application/x-gzip]
Saving to: ‘STDOUT’

-                   100%[===================>]  68.40K   237KB/s    in 0.3s

2017-11-27 08:26:52 (237 KB/s) - written to stdout [70042/70042]

patching file functions
W: Cannot check Release signature; keyring file not available /usr/share/keyrings/debian-archive-keyring.gpg
I: Retrieving InRelease
I: Retrieving Release
I: Retrieving Packages
I: Validating Packages
I: Resolving dependencies of required packages...
I: Resolving dependencies of base packages...
I: Found additional required dependencies: libaudit-common libaudit1 libbz2-1.0 libcap-ng0 libdb5.3 libdebconfclient0 libgcrypt20 libgpg-error0 liblz4-1 libncursesw5 libsemanage-common libsemanage1 libsystemd0 libudev1 libustr-1.0-1
I: Found additional base dependencies: dmsetup gnupg-agent libapparmor1 libassuan0 libbsd0 libcap2 libcryptsetup4 libdevmapper1.02.1 libdns-export162 libelf1 libfastjson4 libffi6 libgmp10 libgnutls30 libhogweed4 libidn11 libidn2-0 libip4tc0 libip6tc0 libiptc0 libisc-export160 libksba8 liblocale-gettext-perl liblognorm5 libmnl0 libncurses5 libnetfilter-conntrack3 libnettle6 libnfnetlink0 libnpth0 libp11-kit0 libpsl5 libseccomp2 libsqlite3-0 libtasn1-6 libtext-charwidth-perl libtext-iconv-perl libtext-wrapi18n-perl libunistring0 libxtables12 pinentry-curses xxd
I: Checking component main on http://deb.debian.org/debian...
I: Retrieving libacl1 2.2.52-3+b1
I: Validating libacl1 2.2.52-3+b1
I: Retrieving adduser 3.115
I: Validating adduser 3.115
I: Retrieving libapparmor1 2.11.0-3
I: Validating libapparmor1 2.11.0-3
I: Retrieving apt 1.4.8
I: Validating apt 1.4.8
I: Retrieving apt-utils 1.4.8
I: Validating apt-utils 1.4.8
I: Retrieving libapt-inst2.0 1.4.8
I: Validating libapt-inst2.0 1.4.8
I: Retrieving libapt-pkg5.0 1.4.8
I: Validating libapt-pkg5.0 1.4.8
I: Retrieving libattr1 1:2.4.47-2+b2
I: Validating libattr1 1:2.4.47-2+b2
I: Retrieving libaudit-common 1:2.6.7-2
I: Validating libaudit-common 1:2.6.7-2
I: Retrieving libaudit1 1:2.6.7-2
I: Validating libaudit1 1:2.6.7-2
I: Retrieving base-files 9.9+deb9u1
I: Validating base-files 9.9+deb9u1
I: Retrieving base-passwd 3.5.43
I: Validating base-passwd 3.5.43
I: Retrieving bash 4.4-5
I: Validating bash 4.4-5
I: Retrieving libdns-export162 1:9.10.3.dfsg.P4-12.3+deb9u3
I: Validating libdns-export162 1:9.10.3.dfsg.P4-12.3+deb9u3
I: Retrieving libisc-export160 1:9.10.3.dfsg.P4-12.3+deb9u3
I: Validating libisc-export160 1:9.10.3.dfsg.P4-12.3+deb9u3
I: Retrieving bsdmainutils 9.0.12+nmu1
I: Validating bsdmainutils 9.0.12+nmu1
I: Retrieving libbz2-1.0 1.0.6-8.1
I: Validating libbz2-1.0 1.0.6-8.1
I: Retrieving libdebconfclient0 0.227
I: Validating libdebconfclient0 0.227
I: Retrieving coreutils 8.26-3
I: Validating coreutils 8.26-3
I: Retrieving cpio 2.11+dfsg-6
I: Validating cpio 2.11+dfsg-6
I: Retrieving cron 3.0pl1-128+b1
I: Validating cron 3.0pl1-128+b1
I: Retrieving libcryptsetup4 2:1.7.3-4
I: Validating libcryptsetup4 2:1.7.3-4
I: Retrieving dash 0.5.8-2.4
I: Validating dash 0.5.8-2.4
I: Retrieving libdb5.3 5.3.28-12+deb9u1
I: Validating libdb5.3 5.3.28-12+deb9u1
I: Retrieving debconf 1.5.61
I: Validating debconf 1.5.61
I: Retrieving debconf-i18n 1.5.61
I: Validating debconf-i18n 1.5.61
I: Retrieving debian-archive-keyring 2017.5
I: Validating debian-archive-keyring 2017.5
I: Retrieving debianutils 4.8.1.1
I: Validating debianutils 4.8.1.1
I: Retrieving diffutils 1:3.5-3
I: Validating diffutils 1:3.5-3
I: Retrieving dmidecode 3.0-4
I: Validating dmidecode 3.0-4
I: Retrieving dpkg 1.18.24
I: Validating dpkg 1.18.24
I: Retrieving e2fslibs 1.43.4-2
I: Validating e2fslibs 1.43.4-2
I: Retrieving e2fsprogs 1.43.4-2
I: Validating e2fsprogs 1.43.4-2
I: Retrieving libcomerr2 1.43.4-2
I: Validating libcomerr2 1.43.4-2
I: Retrieving libss2 1.43.4-2
I: Validating libss2 1.43.4-2
I: Retrieving libelf1 0.168-1
I: Validating libelf1 0.168-1
I: Retrieving findutils 4.6.0+git+20161106-2
I: Validating findutils 4.6.0+git+20161106-2
I: Retrieving gcc-6-base 6.3.0-18
I: Validating gcc-6-base 6.3.0-18
I: Retrieving libgcc1 1:6.3.0-18
I: Validating libgcc1 1:6.3.0-18
I: Retrieving libstdc++6 6.3.0-18
I: Validating libstdc++6 6.3.0-18
I: Retrieving libgdbm3 1.8.3-14
I: Validating libgdbm3 1.8.3-14
I: Retrieving libc-bin 2.24-11+deb9u1
I: Validating libc-bin 2.24-11+deb9u1
I: Retrieving libc6 2.24-11+deb9u1
I: Validating libc6 2.24-11+deb9u1
I: Retrieving multiarch-support 2.24-11+deb9u1
I: Validating multiarch-support 2.24-11+deb9u1
I: Retrieving libgmp10 2:6.1.2+dfsg-1
I: Validating libgmp10 2:6.1.2+dfsg-1
I: Retrieving gnupg 2.1.18-8~deb9u1
I: Validating gnupg 2.1.18-8~deb9u1
I: Retrieving gnupg-agent 2.1.18-8~deb9u1
I: Validating gnupg-agent 2.1.18-8~deb9u1
I: Retrieving gpgv 2.1.18-8~deb9u1
I: Validating gpgv 2.1.18-8~deb9u1
I: Retrieving libgnutls30 3.5.8-5+deb9u3
I: Validating libgnutls30 3.5.8-5+deb9u3
I: Retrieving grep 2.27-2
I: Validating grep 2.27-2
I: Retrieving gzip 1.6-5+b1
I: Validating gzip 1.6-5+b1
I: Retrieving hostname 3.18+b1
I: Validating hostname 3.18+b1
I: Retrieving ifupdown 0.8.19
I: Validating ifupdown 0.8.19
I: Retrieving init 1.48
I: Validating init 1.48
I: Retrieving init-system-helpers 1.48
I: Validating init-system-helpers 1.48
I: Retrieving iproute2 4.9.0-1
I: Validating iproute2 4.9.0-1
I: Retrieving iptables 1.6.0+snapshot20161117-6
I: Validating iptables 1.6.0+snapshot20161117-6
I: Retrieving libip4tc0 1.6.0+snapshot20161117-6
I: Validating libip4tc0 1.6.0+snapshot20161117-6
I: Retrieving libip6tc0 1.6.0+snapshot20161117-6
I: Validating libip6tc0 1.6.0+snapshot20161117-6
I: Retrieving libiptc0 1.6.0+snapshot20161117-6
I: Validating libiptc0 1.6.0+snapshot20161117-6
I: Retrieving libxtables12 1.6.0+snapshot20161117-6
I: Validating libxtables12 1.6.0+snapshot20161117-6
I: Retrieving iputils-ping 3:20161105-1
I: Validating iputils-ping 3:20161105-1
I: Retrieving isc-dhcp-client 4.3.5-3
I: Validating isc-dhcp-client 4.3.5-3
I: Retrieving isc-dhcp-common 4.3.5-3
I: Validating isc-dhcp-common 4.3.5-3
I: Retrieving kmod 23-2
I: Validating kmod 23-2
I: Retrieving libkmod2 23-2
I: Validating libkmod2 23-2
I: Retrieving libassuan0 2.4.3-2
I: Validating libassuan0 2.4.3-2
I: Retrieving libbsd0 0.8.3-1
I: Validating libbsd0 0.8.3-1
I: Retrieving libcap-ng0 0.7.7-3+b1
I: Validating libcap-ng0 0.7.7-3+b1
I: Retrieving libcap2 1:2.25-1
I: Validating libcap2 1:2.25-1
I: Retrieving libestr0 0.1.10-2
I: Validating libestr0 0.1.10-2
I: Retrieving libfastjson4 0.99.4-1
I: Validating libfastjson4 0.99.4-1
I: Retrieving libffi6 3.2.1-6
I: Validating libffi6 3.2.1-6
I: Retrieving libgcrypt20 1.7.6-2+deb9u2
I: Validating libgcrypt20 1.7.6-2+deb9u2
I: Retrieving libgpg-error0 1.26-2
I: Validating libgpg-error0 1.26-2
I: Retrieving libidn11 1.33-1
I: Validating libidn11 1.33-1
I: Retrieving libidn2-0 0.16-1+deb9u1
I: Validating libidn2-0 0.16-1+deb9u1
I: Retrieving libksba8 1.3.5-2
I: Validating libksba8 1.3.5-2
I: Retrieving liblocale-gettext-perl 1.07-3+b1
I: Validating liblocale-gettext-perl 1.07-3+b1
I: Retrieving liblogging-stdlog0 1.0.5-2+b2
I: Validating liblogging-stdlog0 1.0.5-2+b2
I: Retrieving liblognorm5 2.0.1-1.1+b1
I: Validating liblognorm5 2.0.1-1.1+b1
I: Retrieving libmnl0 1.0.4-2
I: Validating libmnl0 1.0.4-2
I: Retrieving libnetfilter-conntrack3 1.0.6-2
I: Validating libnetfilter-conntrack3 1.0.6-2
I: Retrieving libnfnetlink0 1.0.1-3
I: Validating libnfnetlink0 1.0.1-3
I: Retrieving libpipeline1 1.4.1-2
I: Validating libpipeline1 1.4.1-2
I: Retrieving libpsl5 0.17.0-3
I: Validating libpsl5 0.17.0-3
I: Retrieving libseccomp2 2.3.1-2.1
I: Validating libseccomp2 2.3.1-2.1
I: Retrieving libselinux1 2.6-3+b3
I: Validating libselinux1 2.6-3+b3
I: Retrieving libsemanage-common 2.6-2
I: Validating libsemanage-common 2.6-2
I: Retrieving libsemanage1 2.6-2
I: Validating libsemanage1 2.6-2
I: Retrieving libsepol1 2.6-2
I: Validating libsepol1 2.6-2
I: Retrieving libtasn1-6 4.10-1.1
I: Validating libtasn1-6 4.10-1.1
I: Retrieving libtext-charwidth-perl 0.04-7+b3
I: Validating libtext-charwidth-perl 0.04-7+b3
I: Retrieving libtext-iconv-perl 1.7-5+b3
I: Validating libtext-iconv-perl 1.7-5+b3
I: Retrieving libtext-wrapi18n-perl 0.06-7.1
I: Validating libtext-wrapi18n-perl 0.06-7.1
I: Retrieving libunistring0 0.9.6+really0.9.3-0.1
I: Validating libunistring0 0.9.6+really0.9.3-0.1
I: Retrieving logrotate 3.11.0-0.1
I: Validating logrotate 3.11.0-0.1
I: Retrieving lsb-base 9.20161125
I: Validating lsb-base 9.20161125
I: Retrieving dmsetup 2:1.02.137-2
I: Validating dmsetup 2:1.02.137-2
I: Retrieving libdevmapper1.02.1 2:1.02.137-2
I: Validating libdevmapper1.02.1 2:1.02.137-2
I: Retrieving liblz4-1 0.0~r131-2+b1
I: Validating liblz4-1 0.0~r131-2+b1
I: Retrieving mawk 1.3.3-17+b3
I: Validating mawk 1.3.3-17+b3
I: Retrieving nano 2.7.4-1
I: Validating nano 2.7.4-1
I: Retrieving libncurses5 6.0+20161126-1+deb9u1
I: Validating libncurses5 6.0+20161126-1+deb9u1
I: Retrieving libncursesw5 6.0+20161126-1+deb9u1
I: Validating libncursesw5 6.0+20161126-1+deb9u1
I: Retrieving libtinfo5 6.0+20161126-1+deb9u1
I: Validating libtinfo5 6.0+20161126-1+deb9u1
I: Retrieving ncurses-base 6.0+20161126-1+deb9u1
I: Validating ncurses-base 6.0+20161126-1+deb9u1
I: Retrieving ncurses-bin 6.0+20161126-1+deb9u1
I: Validating ncurses-bin 6.0+20161126-1+deb9u1
I: Retrieving netbase 5.4
I: Validating netbase 5.4
I: Retrieving libhogweed4 3.3-1+b2
I: Validating libhogweed4 3.3-1+b2
I: Retrieving libnettle6 3.3-1+b2
I: Validating libnettle6 3.3-1+b2
I: Retrieving libnewt0.52 0.52.19-1+b1
I: Validating libnewt0.52 0.52.19-1+b1
I: Retrieving whiptail 0.52.19-1+b1
I: Validating whiptail 0.52.19-1+b1
I: Retrieving libnpth0 1.3-1
I: Validating libnpth0 1.3-1
I: Retrieving libssl1.1 1.1.0f-3
I: Validating libssl1.1 1.1.0f-3
I: Retrieving libssl1.0.2 1.0.2l-2
I: Validating libssl1.0.2 1.0.2l-2
I: Retrieving libp11-kit0 0.23.3-2
I: Validating libp11-kit0 0.23.3-2
I: Retrieving libpam-modules 1.1.8-3.6
I: Validating libpam-modules 1.1.8-3.6
I: Retrieving libpam-modules-bin 1.1.8-3.6
I: Validating libpam-modules-bin 1.1.8-3.6
I: Retrieving libpam-runtime 1.1.8-3.6
I: Validating libpam-runtime 1.1.8-3.6
I: Retrieving libpam0g 1.1.8-3.6
I: Validating libpam0g 1.1.8-3.6
I: Retrieving libpcre3 2:8.39-3
I: Validating libpcre3 2:8.39-3
I: Retrieving perl-base 5.24.1-3+deb9u2
I: Validating perl-base 5.24.1-3+deb9u2
I: Retrieving pinentry-curses 1.0.0-2
I: Validating pinentry-curses 1.0.0-2
I: Retrieving libpopt0 1.16-10+b2
I: Validating libpopt0 1.16-10+b2
I: Retrieving libprocps6 2:3.3.12-3
I: Validating libprocps6 2:3.3.12-3
I: Retrieving procps 2:3.3.12-3
I: Validating procps 2:3.3.12-3
I: Retrieving libreadline7 7.0-3
I: Validating libreadline7 7.0-3
I: Retrieving readline-common 7.0-3
I: Validating readline-common 7.0-3
I: Retrieving rsyslog 8.24.0-1
I: Validating rsyslog 8.24.0-1
I: Retrieving sed 4.4-1
I: Validating sed 4.4-1
I: Retrieving sensible-utils 0.0.9
I: Validating sensible-utils 0.0.9
I: Retrieving login 1:4.4-4.1
I: Validating login 1:4.4-4.1
I: Retrieving passwd 1:4.4-4.1
I: Validating passwd 1:4.4-4.1
I: Retrieving libslang2 2.3.1-5
I: Validating libslang2 2.3.1-5
I: Retrieving libsqlite3-0 3.16.2-5
I: Validating libsqlite3-0 3.16.2-5
I: Retrieving libsystemd0 232-25+deb9u1
I: Validating libsystemd0 232-25+deb9u1
I: Retrieving libudev1 232-25+deb9u1
I: Validating libudev1 232-25+deb9u1
I: Retrieving systemd 232-25+deb9u1
I: Validating systemd 232-25+deb9u1
I: Retrieving systemd-sysv 232-25+deb9u1
I: Validating systemd-sysv 232-25+deb9u1
I: Retrieving udev 232-25+deb9u1
I: Validating udev 232-25+deb9u1
I: Retrieving sysvinit-utils 2.88dsf-59.9
I: Validating sysvinit-utils 2.88dsf-59.9
I: Retrieving tar 1.29b-1.1
I: Validating tar 1.29b-1.1
I: Retrieving tasksel 3.39
I: Validating tasksel 3.39
I: Retrieving tasksel-data 3.39
I: Validating tasksel-data 3.39
I: Retrieving tzdata 2017b-1
I: Validating tzdata 2017b-1
I: Retrieving libustr-1.0-1 1.0.4-6
I: Validating libustr-1.0-1 1.0.4-6
I: Retrieving bsdutils 1:2.29.2-1
I: Validating bsdutils 1:2.29.2-1
I: Retrieving libblkid1 2.29.2-1
I: Validating libblkid1 2.29.2-1
I: Retrieving libfdisk1 2.29.2-1
I: Validating libfdisk1 2.29.2-1
I: Retrieving libmount1 2.29.2-1
I: Validating libmount1 2.29.2-1
I: Retrieving libsmartcols1 2.29.2-1
I: Validating libsmartcols1 2.29.2-1
I: Retrieving libuuid1 2.29.2-1
I: Validating libuuid1 2.29.2-1
I: Retrieving mount 2.29.2-1
I: Validating mount 2.29.2-1
I: Retrieving util-linux 2.29.2-1
I: Validating util-linux 2.29.2-1
I: Retrieving vim-common 2:8.0.0197-4+deb9u1
I: Validating vim-common 2:8.0.0197-4+deb9u1
I: Retrieving vim-tiny 2:8.0.0197-4+deb9u1
I: Validating vim-tiny 2:8.0.0197-4+deb9u1
I: Retrieving xxd 2:8.0.0197-4+deb9u1
I: Validating xxd 2:8.0.0197-4+deb9u1
I: Retrieving wget 1.18-5
I: Validating wget 1.18-5
I: Retrieving libxapian30 1.4.3-2
I: Validating libxapian30 1.4.3-2
I: Retrieving liblzma5 5.2.2-1.2+b1
I: Validating liblzma5 5.2.2-1.2+b1
I: Retrieving zlib1g 1:1.2.8.dfsg-5
I: Validating zlib1g 1:1.2.8.dfsg-5
I: Chosen extractor for .deb packages: dpkg-deb
I: Extracting libacl1...
I: Extracting libattr1...
I: Extracting libaudit-common...
I: Extracting libaudit1...
I: Extracting base-files...
I: Extracting base-passwd...
I: Extracting bash...
I: Extracting libbz2-1.0...
I: Extracting libdebconfclient0...
I: Extracting coreutils...
I: Extracting dash...
I: Extracting libdb5.3...
I: Extracting debconf...
I: Extracting debianutils...
I: Extracting diffutils...
I: Extracting dpkg...
I: Extracting e2fslibs...
I: Extracting e2fsprogs...
I: Extracting libcomerr2...
I: Extracting libss2...
I: Extracting findutils...
I: Extracting gcc-6-base...
I: Extracting libgcc1...
I: Extracting libc-bin...
I: Extracting libc6...
I: Extracting multiarch-support...
I: Extracting grep...
I: Extracting gzip...
I: Extracting hostname...
I: Extracting init-system-helpers...
I: Extracting libcap-ng0...
I: Extracting libgcrypt20...
I: Extracting libgpg-error0...
I: Extracting libselinux1...
I: Extracting libsemanage-common...
I: Extracting libsemanage1...
I: Extracting libsepol1...
I: Extracting lsb-base...
I: Extracting liblz4-1...
I: Extracting mawk...
I: Extracting libncursesw5...
I: Extracting libtinfo5...
I: Extracting ncurses-base...
I: Extracting ncurses-bin...
I: Extracting libpam-modules...
I: Extracting libpam-modules-bin...
I: Extracting libpam-runtime...
I: Extracting libpam0g...
I: Extracting libpcre3...
I: Extracting perl-base...
I: Extracting sed...
I: Extracting sensible-utils...
I: Extracting login...
I: Extracting passwd...
I: Extracting libsystemd0...
I: Extracting libudev1...
I: Extracting sysvinit-utils...
I: Extracting tar...
I: Extracting tzdata...
I: Extracting libustr-1.0-1...
I: Extracting bsdutils...
I: Extracting libblkid1...
I: Extracting libfdisk1...
I: Extracting libmount1...
I: Extracting libsmartcols1...
I: Extracting libuuid1...
I: Extracting mount...
I: Extracting util-linux...
I: Extracting liblzma5...
I: Extracting zlib1g...
I: Keyring file not available at /usr/share/keyrings/debian-archive-keyring.gpg; switching to https mirror https://deb.debian.org/debian
I: Installing core packages...
W: Failure trying to run:  dpkg --force-depends --install /var/cache/apt/archives/base-passwd_3.5.43_arm64.deb
W: See //debootstrap/debootstrap.log for details (possibly the package /var/cache/apt/archives/base-passwd_3.5.43_arm64.deb is at fault)
update-alternatives: error: no alternatives for editor
info: Trying to set 'debconf/frontend' [select] to 'Editor'
info: Loading answer for 'debconf/frontend'
info: Trying to set 'debconf/priority' [select] to 'low'
info: Loading answer for 'debconf/priority'
info: Trying to set 'locales/locales_to_be_generated' [select] to 'en_US.UTF-8 UTF-8'
info: Loading answer for 'locales/locales_to_be_generated'
info: Trying to set 'locales/default_environment_locale' [select] to 'en_US.UTF-8'
info: Loading answer for 'locales/default_environment_locale'
dpkg-query: warning: parsing file '/var/lib/dpkg/status' near line 24 package 'dpkg':
 missing description
dpkg-query: warning: parsing file '/var/lib/dpkg/status' near line 24 package 'dpkg':
 missing architecture
dpkg-query: warning: parsing file '/var/lib/dpkg/status' near line 24 package 'dpkg':
 missing description
dpkg-query: warning: parsing file '/var/lib/dpkg/status' near line 24 package 'dpkg':
 missing architecture
dpkg-query: package 'tzdata' is not installed and no information is available
Use dpkg --info (= dpkg-deb --info) to examine archive files,
and dpkg --contents (= dpkg-deb --contents) to list their contents.
/usr/sbin/dpkg-reconfigure: tzdata is not installed
dpkg-query: warning: parsing file '/var/lib/dpkg/status' near line 24 package 'dpkg':
 missing description
dpkg-query: warning: parsing file '/var/lib/dpkg/status' near line 24 package 'dpkg':
 missing architecture
dpkg-query: warning: parsing file '/var/lib/dpkg/status' near line 24 package 'dpkg':
 missing description
dpkg-query: warning: parsing file '/var/lib/dpkg/status' near line 24 package 'dpkg':
 missing architecture
dpkg-query: package 'debconf' is not installed and no information is available
Use dpkg --info (= dpkg-deb --info) to examine archive files,
and dpkg --contents (= dpkg-deb --contents) to list their contents.
/usr/sbin/dpkg-reconfigure: debconf is not installed
/tmp/dot_tmp.sh: 26: /tmp/dot_tmp.sh: apt: not found
/tmp/dot_tmp.sh: 27: /tmp/dot_tmp.sh: apt: not found
/tmp/dot_tmp.sh: 28: /tmp/dot_tmp.sh: apt: not found
/tmp/dot_tmp.sh: 29: /tmp/dot_tmp.sh: update-locale: not found
/tmp/dot_tmp.sh: 34: /tmp/dot_tmp.sh: apt: not found

installation successfully completed
to enter the guest system type:
$HOME/bin/enter_deb

bash-4.4$

```

```
bash-4.4$ git diff origin
diff --git a/debian_on_termux.sh b/debian_on_termux.sh
index b619c34..f8da305 100755
--- a/debian_on_termux.sh
+++ b/debian_on_termux.sh
@@ -9,7 +9,7 @@ DO_FIRST_STAGE=: # false   # required (unpack phase/ executes outside guest invi
 DO_SECOND_STAGE=: # false  # required (complete the install/ executes inside guest invironment)
 DO_THIRD_STAGE=: # false   # optional (enable local policies/ executes inside guest invironment)

-ARCHITECTURE=armhf         # supported architectures include: armel, armhf, arm64, i386, amd64
+ARCHITECTURE=arm64         # supported architectures include: armel, armhf, arm64, i386, amd64
 VERSION=stretch            # supported debian versions include: stretch, stable, testing, unstable
 ROOTFS_TOP=deboot_debian   # name of the top install directory
 ZONEINFO=Europe/Berlin     # set your desired time zone
bash-4.4$
```

```
```

**Comment by tumashu** [comment] 2017-11-27 02:49
```
bash-4.4$ cat debootstrap.log
setup_devices_simple
setup_proc
dpkg: warning: parsing file '/var/lib/dpkg/status' near line 5 package 'dpkg':
 missing description
dpkg: warning: parsing file '/var/lib/dpkg/status' near line 5 package 'dpkg':
 missing architecture
Selecting previously unselected package base-passwd.
(Reading database ... 0 files and directories currently installed.)
Preparing to unpack .../base-passwd_3.5.43_arm64.deb ...
Unpacking base-passwd (3.5.43) ...
dpkg: error processing archive /var/cache/apt/archives/base-passwd_3.5.43_arm64.deb (--install):
 unable to securely remove '/usr/sbin/update-passwd.dpkg-tmp': Operation not permitted
Errors were encountered while processing:
 /var/cache/apt/archives/base-passwd_3.5.43_arm64.deb

```

**Comment by sdrausty** [comment] 2017-12-03 17:27
Thanks for making this script available.  It works fine on arm7.  Does not work on arm64.  `apt` prerequisites fail to install.  I tried all available Debian versions on arm64, and all fail at this step.  Is this a problem with our version of debootstrap?

**Comment by sdrausty** [comment] 2017-12-03 17:51
I think that this is an upstream issue.  I have the same error when using `debootstrap --verbose --arch=arm64 --include=apt stable stable http://ftp.debian.org/debian/` in Arch Linux in Termux PRoot.

![screenshot_20171203-124803](https://user-images.githubusercontent.com/27742457/33528017-83803b5e-d828-11e7-802f-3b08065e4517.png)

**Comment by sp4rkie** [comment] 2017-12-03 19:16
wow, thanks for digging this. 

I couldn't reproduce the problem yet since I only have 32 bit devices around. Except I could try the 64bit emulator and try if it fails there too. It's hard for me to diagnose the issue without reproducing it on my own devices. Thanks to you we are a big step further anyway.

**Comment by tumashu** [comment] 2017-12-03 23:54
Wow, thanks for hard work!

**Comment by sdrausty** [comment] 2017-12-09 09:57
`$ debootstrap --version
debootstrap 1.0.93` is available for Arch Linux in Termux PRoot.

**Comment by sp4rkie** [comment] 2017-12-09 12:01
thanks for hinting this. 

I now upgraded to 1.0.93. Could anybody with the issue (i.e. architecture arm64) please test if that fixes the issue?

At least 'armhf' still works without issues so far.

**Comment by sdrausty** [comment] 2017-12-09 16:08
The results are still the same on arm64 when installing for arm64.  There is a new debootstrap in the works for Termux.  https://github.com/termux/termux-packages/pull/1915  Hopefully it will be available soon.  
![screenshot_20171209-105921](https://user-images.githubusercontent.com/27742457/33797136-a297c456-dcd0-11e7-9fac-9aba838ec648.png)

**Comment by xeffyr** [comment] 2017-12-09 19:39
Is someone still have error when installling base-passwd package ?

Error details is:
```
dpkg: error processing archive /var/cache/apt/archives/base-passwd_3.5.43_arm64.deb (--install):
 unable to securely remove '/usr/sbin/update-passwd.dpkg-tmp': Operation not permitted
```

The problem is that **link2symlink in proot doesn't work correctly**: if link2symlink was removed from all debootstrap scripts, then everything installs fine (if SELinux in permissive mode).

**Comment by sp4rkie** [comment] 2017-12-10 07:05
interesting!

since I patch `debootstrap` anyway I could simply include the `link2symlink` thing in my patch. Until the issue gets fixed in `proot`.

what do you mean by `if link2symlink was removed from all debootstrap scripts,`?
Do you replace `ln -sf` by something else?

**Comment by sp4rkie** [comment] 2018-02-27 16:25
the original issue '/tmp/dot_tmp.sh: 26: /tmp/dot_tmp.sh: apt: not found' is  fixed in the current version.

Regarding the 'proot' issues: there is a new version out now as well. Please retry.

Thanks for reporting.

**Closed by sp4rkie** 2018-02-27 16:25 UTC
