### ISSUE TITLE
APT Command not found.

### ISSUE THREAD

**Issue by Deathlive** [sp4rkie/debian-on-termux#5] opened 2017-11-13 08:11 UTC
```
root@localhost:~# apt update
bash: apt: command not found
root@localhost:~# apt-get update
bash: apt-get: command not found
root@localhost:~# env
LANG=en_US.UTF-8
PWD=/root
HOME=/root
TERM=xterm-256color
SHLVL=1
PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
_=/usr/bin/env
root@localhost:~#uname -a
Linux localhost 3.10.72 #1 SMP PREEMPT Mon Aug 22 19:58:28 CST 2016 armv7l GNU/Linux
root@localhost:~# more /etc/debian_version
9.1
```
installed from scratch, on a pure termux.

**Comment by sp4rkie** [comment] 2017-11-13 14:37
strange. maybe a duplicate of #6 . Could you please retest the new version?

**Closed** 2017-11-13 15:55 UTC

**Comment by mark-orion** [comment] 2018-01-14 20:04
Same here: Although I get a message 'installation successfully completed' this is not true. Errors before the end of the script - apt is not even available during the install.

: Extracting zlib1g...
I: Keyring file not available at /usr/share/keyrings/debian-archive-keyring.gpg; switching to https mirror https://deb.debian.org/debian
I: Installing core packages...
W: Failure trying to run:  dpkg --force-depends --install /var/cache/apt/archives/base-passwd_3.5.43_arm64.deb
W: See //debootstrap/debootstrap.log for details (possibly the package /var/cache/apt/archives/base-passwd_3.5.43_arm64.deb is at fault)
update-alternatives: error: no alternatives for editor
info: Trying to set 'debconf/frontend' [select] to 'Editor'
info: Loading answer for 'debconf/frontend'
info: Trying to set 'debconf/priority' [select] to 'low'
info: Loading answer for 'debconf/priority'                                                                                                       info: Trying to set 'locales/locales_to_be_generated' [select] to 'en_US.UTF-8 UTF-8'
info: Loading answer for 'locales/locales_to_be_generated'                                                                                        info: Trying to set 'locales/default_environment_locale' [select] to 'en_US.UTF-8'                                                                info: Loading answer for 'locales/default_environment_locale'                                                                                     dpkg-query: warning: parsing file '/var/lib/dpkg/status' near line 24 package 'dpkg':
 missing description
dpkg-query: warning: parsing file '/var/lib/dpkg/status' near line 24 package 'dpkg':
 missing architecture
dpkg-query: warning: parsing file '/var/lib/dpkg/status' near line 24 package 'dpkg':
 missing description
dpkg-query: warning: parsing file '/var/lib/dpkg/status' near line 24 package 'dpkg':
 missing architecture
dpkg-query: package 'tzdata' is not installed and no information is available
Use dpkg --info (= dpkg-deb --info) to examine archive files,
and dpkg --contents (= dpkg-deb --contents) to list their contents.
/usr/sbin/dpkg-reconfigure: tzdata is not installed
dpkg-query: warning: parsing file '/var/lib/dpkg/status' near line 24 package 'dpkg':
 missing description
dpkg-query: warning: parsing file '/var/lib/dpkg/status' near line 24 package 'dpkg':
 missing architecture
dpkg-query: warning: parsing file '/var/lib/dpkg/status' near line 24 package 'dpkg':
 missing description
dpkg-query: warning: parsing file '/var/lib/dpkg/status' near line 24 package 'dpkg':
 missing architecture
dpkg-query: package 'debconf' is not installed and no information is available
Use dpkg --info (= dpkg-deb --info) to examine archive files,
and dpkg --contents (= dpkg-deb --contents) to list their contents.
/usr/sbin/dpkg-reconfigure: debconf is not installed
/tmp/dot_tmp.sh: 26: /tmp/dot_tmp.sh: apt: not found
/tmp/dot_tmp.sh: 27: /tmp/dot_tmp.sh: apt: not found
/tmp/dot_tmp.sh: 28: /tmp/dot_tmp.sh: apt: not found
/tmp/dot_tmp.sh: 29: /tmp/dot_tmp.sh: update-locale: not found
/tmp/dot_tmp.sh: 34: /tmp/dot_tmp.sh: apt: not found

installation successfully completed
to enter the guest system type:
$HOME/bin/enter_deb
