### ISSUE TITLE
Systemd causes installation fail

### ISSUE THREAD

**Issue by sandworm88** [sp4rkie/debian-on-termux#49] opened 2019-06-19 11:56 UTC
Please remove systemd from installation list. It makes installation fail. Moreover it's not needed :)
```
Setting up systemd (232-25+deb9u11) ...
Created symlink /etc/systemd/system/getty.target.wants/getty@tty1.service -> /lib/systemd/system/getty@.service.
Created symlink /etc/systemd/system/multi-user.target.wants/remote-fs.target -> /lib/systemd/system/remote-fs.target.
Created symlink /etc/systemd/system/sysinit.target.wants/systemd-timesyncd.service -> /lib/systemd/system/systemd-timesyncd.service.
Initializing machine ID from random generator.
Adding group `systemd-journal' (GID 101) ...
Done.
chfn: PAM: System error
adduser: `/usr/bin/chfn -f systemd Time Synchronization systemd-timesync' returned error code 1. Exiting.
dpkg: error processing package systemd (--install):
 subprocess installed post-installation script returned error exit status 1
```

**Comment by Dmole** [comment] 2019-06-25 13:37
https://github.com/sp4rkie/debian-on-termux/blob/master/README.md#issues

**Comment by sp4rkie** [comment] 2020-03-04 13:46
the problem is out of scope of debian-on-termux. But it appears to be fixed in debootstrap_1.0.119 anyway

please check 'deboot_debian/var/log/bootstrap.log' near the lines 'Setting up systemd' after the installation finished:

        [...]
        Setting up libcryptsetup12:arm64 (2:2.1.0-5+deb10u2) ...
        Setting up dmsetup (2:1.02.155-3) ...
        Setting up systemd (241-7~deb10u3) ...
        Created symlink /etc/systemd/system/getty.target.wants/getty@tty1.service -> /lib/systemd/system/getty@.service.
        Created symlink /etc/systemd/system/multi-user.target.wants/remote-fs.target -> /lib/systemd/system/remote-fs.target.
        Created symlink /etc/systemd/system/dbus-org.freedesktop.timesync1.service -> /lib/systemd/system/systemd-timesyncd.service.
        Created symlink /etc/systemd/system/sysinit.target.wants/systemd-timesyncd.service -> /lib/systemd/system/systemd-timesyncd.service.
        Initializing machine ID from random generator.
        Processing triggers for libc-bin (2.28-10) ...
        (Reading database ... 7307 files and directories currently installed.)
        Preparing to unpack .../systemd-sysv_241-7~deb10u3_arm64.deb ...
        Unpacking systemd-sysv (241-7~deb10u3) ...
        Setting up systemd-sysv (241-7~deb10u3) ...
        (Reading database ... 7324 files and directories currently installed.)
        Preparing to unpack .../apt-utils_1.8.2_arm64.deb ...
        Unpacking apt-utils (1.8.2) ...
        [...]

**Closed by sp4rkie** 2020-03-04 13:46 UTC
